spring:
  application:
    name: currency-exchange-service
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      register-mbeans: true
      driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8090
logging:
  level: info
  path: ./app_data/
  file: app.log
